- name: Template DO
  template:
    src: "f5_do_template.j2"
    dest: "{{ backup_dir }}/yaml/{{ inventory_hostname }}_do.yml"
  diff: yes
  

- name: Set facts from generated yaml
  shell: "cat {{ backup_dir }}/yaml/{{ inventory_hostname }}_do.yml"
  register: yaml_result
  changed_when: false

- name: Generate DO in JSON
  copy:
    content: "{{ yaml_result.stdout | from_yaml | to_nice_json }}"
    dest: "{{ backup_dir }}/json/{{ inventory_hostname }}_do.json"

- name: Validate DO using jsonschema
  ansible.utils.validate:
    data: "{{ lookup('file', '{{ backup_dir }}/json/{{ inventory_hostname }}_do.json') }}"
    criteria: "{{ lookup('file', '{{ role_path }}/base.schema.json') }}"